### ISSUE TITLE
It can not run in jdk 1.7

### ISSUE THREAD

**Issue by medzeus2** [RamosLi/dbay-apns-for-java#20]
When i use dbay_apns push apns on jdk 1.7 it returns as follows.
2015-11-04 13:57:44,257 [result]-[INFO] pro-1 Received error response. status: 8, id: 101, error-desc: Invalid token

JDK 1.7U79 x64
APNS Production Certification
The token can be send on Jdk 1.6u45 and works fine.

**Comment by yangwenmai** [comment]
你得保证APNS Production Certification生成p12文件也是相同的JDK版本。

**Comment by medzeus2** [comment]
I used “key chain” in OSX EI capitan to export p12 certification, Not use java..
